name: First job
on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd 
          ls -alF
  my_second_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update 
          sudo apt-get install tree 
        tree -F .     
